#include <hypervisor.h>

/* field encoding and naming */
typedef struct {
	uint32_t		encoding;
	uint32_t		pad;
	const char		*name;
} vmcs_encoding_t;

#define str(x) #x
#define CONSTRUCT_ACRN_VMCS_ENCODING(id, encoding) [id] = {encoding, 0, str(id)}

#if 0
typedef enum {
	/*SW writable, CPU readonly*/
	ACRN_VMCS_VPID = 0,
	ACRN_VMCS_IO_BITMAP_A,
	ACRN_VMCS_IO_BITMAP_B,
	ACRN_VMCS_MSR_BITMAP,
	ACRN_VMCS_TSC_OFFSET,
	ACRN_VMCS_VIRTUAL_APIC_ADDR,     // for virtual apic
        ACRN_VMCS_APIC_ACCESS_ADDR,      // for virtual apic
        ACRN_VMCS_POST_INTR_NOTI_VECTOR, // for virtual apic
        ACRN_VMCS_POST_INTR_DESC_ADDR,   // for virtual apic
        ACRN_VMCS_EOI_EXIT_BITMAP0,      // for virtual apic
        ACRN_VMCS_EOI_EXIT_BITMAP1,      // for virtual apic
        ACRN_VMCS_EOI_EXIT_BITMAP2,      // for virtual apic
        ACRN_VMCS_EOI_EXIT_BITMAP3,      // for virtual apic
        ACRN_VMCS_TPR_THRESHOLD,         // for virtual apic
	ACRN_VMCS_EPTP_ADDRESS,
	ACRN_VMCS_XSS_EXIT_BITMAP,
	ACRN_VMCS_PIN_CTRL,
	ACRN_VMCS_PROC_CTRL1,
	ACRN_VMCS_PROC_CTRL2,
	ACRN_VMCS_EXIT_CTRL,
	ACRN_VMCS_CR0_MASK,
	ACRN_VMCS_CR4_MASK,
	ACRN_VMCS_CR0_SHADOW,
	ACRN_VMCS_CR4_SHADOW,
	ACRN_VMCS_CR3_TARGET0,
	ACRN_VMCS_CR3_TARGET1,
	ACRN_VMCS_CR3_TARGET2,
	ACRN_VMCS_CR3_TARGET3,
	ACRN_VMCS_LINK_PTR,
	ACRN_VMCS_EXECUTIVE_VMCS_PTR,
	ACRN_VMCS_PLE_GAP,
	ACRN_VMCS_PLE_WINDOW,
	ACRN_VMCS_VMFUNC_CTRL,
	ACRN_VMCS_EPTP_LIST_ADDR,
	ACRN_VMCS_VMREAD_BITMAP_ADDR,
	ACRN_VMCS_VMWRITE_BITMAP_ADDR,
	ACRN_VMCS_ENCLS_EXIT_BITMAP,
	ACRN_VMCS_PML_ADDR,
	ACRN_VMCS_VIRT_EXCEPT_INFO_ADDR,
	ACRN_VMCS_EPTP_INDEX,
	ACRN_VMCS_HOST_CR0,
	ACRN_VMCS_HOST_CR3,
	ACRN_VMCS_HOST_CR4,
	ACRN_VMCS_HOST_ES_SEL,
	ACRN_VMCS_HOST_CS_SEL,
	ACRN_VMCS_HOST_SS_SEL,
	ACRN_VMCS_HOST_DS_SEL,
	ACRN_VMCS_HOST_FS_SEL,
	ACRN_VMCS_HOST_FS_BASE,
	ACRN_VMCS_HOST_GS_SEL,
	ACRN_VMCS_HOST_GS_BASE,
	ACRN_VMCS_HOST_TR_SEL,
	ACRN_VMCS_HOST_TR_BASE,
	ACRN_VMCS_HOST_GDTR_BASE,
	ACRN_VMCS_HOST_IDTR_BASE,
	ACRN_VMCS_HOST_RSP,
	ACRN_VMCS_HOST_RIP,
	ACRN_VMCS_HOST_PAT,
	ACRN_VMCS_HOST_EFER,
	ACRN_VMCS_HOST_PERF_G_CTRL,
	ACRN_VMCS_EXIT_MSR_STORE_COUNT,     // init as 0 (see dirty_bitmap in vmcs_create)
	                               // = ACRN_VMCS_INIT_TO_ZERO_FISRT
	ACRN_VMCS_EXIT_MSR_STORE_ADDR,      // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_EXIT_MSR_LOAD_COUNT,      // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_EXIT_MSR_LOAD_ADDR,       // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_ENTRY_MSR_LOAD_COUNT,     // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_ENTRY_MSR_LOAD_ADDR,      // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_EXCEPTION_BITMAP,         // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_HOST_SYSENTER_CS,         // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_HOST_SYSENTER_ESP,        // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_HOST_SYSENTER_EIP,        // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_CR3_TARGET_COUNT,         // init as 0 (see dirty_bitmap in vmcs_create)
	/*SW rw, CPU rw*/
	ACRN_VMCS_ENTRY_INTR_INFO,          // init as 0 (see dirty_bitmap in vmcs_create)
	                               // = ACRN_VMCS_ALWAYS_VALID_COUNT
	ACRN_VMCS_GUEST_DBGCTL,             // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_GUEST_INTERRUPTIBILITY,   // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_GUEST_INTERRUPT_STATUS,   // for virtual apic
	ACRN_VMCS_GUEST_PEND_DBG_EXCEPTION, // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_ENTRY_ERR_CODE,           // init as 0 (see dirty_bitmap in vmcs_create)
	                               // = ACRN_VMCS_INIT_TO_ZERO_LAST
	ACRN_VMCS_ENTRY_CTRL,
	ACRN_VMCS_ENTRY_INSTR_LEN,
	ACRN_VMCS_PREEMPTION_TIMER,
	ACRN_VMCS_GUEST_PAT,
	ACRN_VMCS_GUEST_EFER,
	ACRN_VMCS_GUEST_PERF_G_CTRL,
	ACRN_VMCS_GUEST_PDPTR0,
	ACRN_VMCS_GUEST_PDPTR1,
	ACRN_VMCS_GUEST_PDPTR2,
	ACRN_VMCS_GUEST_PDPTR3,
	ACRN_VMCS_GUEST_CR0,
	ACRN_VMCS_GUEST_CR3,
	ACRN_VMCS_GUEST_CR4,
	ACRN_VMCS_GUEST_DR7,
	ACRN_VMCS_GUEST_GDTR_BASE,
	ACRN_VMCS_GUEST_GDTR_LIMIT,
	ACRN_VMCS_GUEST_IDTR_BASE,
	ACRN_VMCS_GUEST_IDTR_LIMIT,
	ACRN_VMCS_GUEST_ACTIVITY_STATE,
	ACRN_VMCS_GUEST_SYSENTER_CS,
	ACRN_VMCS_GUEST_SYSENTER_ESP,
	ACRN_VMCS_GUEST_SYSENTER_EIP,
	ACRN_VMCS_GUEST_ES_SEL,
	ACRN_VMCS_GUEST_ES_BASE,
	ACRN_VMCS_GUEST_ES_LIMIT,
	ACRN_VMCS_GUEST_ES_AR,
	ACRN_VMCS_GUEST_CS_SEL,
	ACRN_VMCS_GUEST_CS_BASE,
	ACRN_VMCS_GUEST_CS_LIMIT,
	ACRN_VMCS_GUEST_CS_AR,
	ACRN_VMCS_GUEST_SS_SEL,
	ACRN_VMCS_GUEST_SS_BASE,
	ACRN_VMCS_GUEST_SS_LIMIT,
	ACRN_VMCS_GUEST_SS_AR,
	ACRN_VMCS_GUEST_DS_SEL,
	ACRN_VMCS_GUEST_DS_BASE,
	ACRN_VMCS_GUEST_DS_LIMIT,
	ACRN_VMCS_GUEST_DS_AR,
	ACRN_VMCS_GUEST_FS_SEL,
	ACRN_VMCS_GUEST_FS_BASE,
	ACRN_VMCS_GUEST_FS_LIMIT,
	ACRN_VMCS_GUEST_FS_AR,
	ACRN_VMCS_GUEST_GS_SEL,
	ACRN_VMCS_GUEST_GS_BASE,
	ACRN_VMCS_GUEST_GS_LIMIT,
	ACRN_VMCS_GUEST_GS_AR,
	ACRN_VMCS_GUEST_LDTR_SEL,
	ACRN_VMCS_GUEST_LDTR_BASE,
	ACRN_VMCS_GUEST_LDTR_LIMIT,
	ACRN_VMCS_GUEST_LDTR_AR,
	ACRN_VMCS_GUEST_TR_SEL,
	ACRN_VMCS_GUEST_TR_BASE,
	ACRN_VMCS_GUEST_TR_LIMIT,
	ACRN_VMCS_GUEST_TR_AR,
	ACRN_VMCS_GUEST_RSP,
	ACRN_VMCS_GUEST_RIP,
	ACRN_VMCS_GUEST_RFLAGS,
	/*SW readonly, CPU writable*/
	ACRN_VMCS_GUEST_PHY_ADDR,
	ACRN_VMCS_GUEST_LINEAR_ADDR,
	ACRN_VMCS_INSTR_ERROR,
	ACRN_VMCS_EXIT_REASON,
	ACRN_VMCS_EXIT_INT_INFO,
	ACRN_VMCS_EXIT_INT_ERR_CODE,
	ACRN_VMCS_IDT_VECTOR_INFO,
	ACRN_VMCS_IDT_VECTOR_ERR_CODE,
	ACRN_VMCS_EXIT_INSTR_LEN,
	ACRN_VMCS_EXIT_INSTR_INFO,
	ACRN_VMCS_EXIT_QUAL,
	ACRN_VMCS_FIELD_COUNT
} vmcs_field_t;
#endif

typedef enum {
	ACRN_VMCS_GUEST_DBGCTL,             // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_GUEST_INTERRUPTIBILITY,   // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_GUEST_INTERRUPT_STATUS,   // for virtual apic
	ACRN_VMCS_GUEST_PEND_DBG_EXCEPTION, // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_PREEMPTION_TIMER,
	ACRN_VMCS_GUEST_PAT,
	ACRN_VMCS_GUEST_EFER,
	ACRN_VMCS_GUEST_PERF_G_CTRL,
	ACRN_VMCS_GUEST_PDPTR0,
	ACRN_VMCS_GUEST_PDPTR1,
	ACRN_VMCS_GUEST_PDPTR2,
	ACRN_VMCS_GUEST_PDPTR3,
	ACRN_VMCS_GUEST_CR0,
	ACRN_VMCS_GUEST_CR3,
	ACRN_VMCS_GUEST_CR4,
	ACRN_VMCS_GUEST_DR7,
	ACRN_VMCS_GUEST_GDTR_BASE,
	ACRN_VMCS_GUEST_GDTR_LIMIT,
	ACRN_VMCS_GUEST_IDTR_BASE,
	ACRN_VMCS_GUEST_IDTR_LIMIT,
	ACRN_VMCS_GUEST_ACTIVITY_STATE,
	ACRN_VMCS_GUEST_SYSENTER_CS,
	ACRN_VMCS_GUEST_SYSENTER_ESP,
	ACRN_VMCS_GUEST_SYSENTER_EIP,
	ACRN_VMCS_GUEST_ES_SEL,
	ACRN_VMCS_GUEST_ES_BASE,
	ACRN_VMCS_GUEST_ES_LIMIT,
	ACRN_VMCS_GUEST_ES_AR,
	ACRN_VMCS_GUEST_CS_SEL,
	ACRN_VMCS_GUEST_CS_BASE,
	ACRN_VMCS_GUEST_CS_LIMIT,
	ACRN_VMCS_GUEST_CS_AR,
	ACRN_VMCS_GUEST_SS_SEL,
	ACRN_VMCS_GUEST_SS_BASE,
	ACRN_VMCS_GUEST_SS_LIMIT,
	ACRN_VMCS_GUEST_SS_AR,
	ACRN_VMCS_GUEST_DS_SEL,
	ACRN_VMCS_GUEST_DS_BASE,
	ACRN_VMCS_GUEST_DS_LIMIT,
	ACRN_VMCS_GUEST_DS_AR,
	ACRN_VMCS_GUEST_FS_SEL,
	ACRN_VMCS_GUEST_FS_BASE,
	ACRN_VMCS_GUEST_FS_LIMIT,
	ACRN_VMCS_GUEST_FS_AR,
	ACRN_VMCS_GUEST_GS_SEL,
	ACRN_VMCS_GUEST_GS_BASE,
	ACRN_VMCS_GUEST_GS_LIMIT,
	ACRN_VMCS_GUEST_GS_AR,
	ACRN_VMCS_GUEST_LDTR_SEL,
	ACRN_VMCS_GUEST_LDTR_BASE,
	ACRN_VMCS_GUEST_LDTR_LIMIT,
	ACRN_VMCS_GUEST_LDTR_AR,
	ACRN_VMCS_GUEST_TR_SEL,
	ACRN_VMCS_GUEST_TR_BASE,
	ACRN_VMCS_GUEST_TR_LIMIT,
	ACRN_VMCS_GUEST_TR_AR,
	ACRN_VMCS_GUEST_RSP,
	ACRN_VMCS_GUEST_RIP,
	ACRN_VMCS_GUEST_RFLAGS,
	ACRN_VMCS_LINK_PTR,

	ACRN_VMCS_GUEST_END
} vmcs_guest_field_t;

typedef enum {
	ACRN_VMCS_HOST_CR0 = ACRN_VMCS_GUEST_END,
	ACRN_VMCS_HOST_CR3,
	ACRN_VMCS_HOST_CR4,
	ACRN_VMCS_HOST_ES_SEL,
	ACRN_VMCS_HOST_CS_SEL,
	ACRN_VMCS_HOST_SS_SEL,
	ACRN_VMCS_HOST_DS_SEL,
	ACRN_VMCS_HOST_FS_SEL,
	ACRN_VMCS_HOST_FS_BASE,
	ACRN_VMCS_HOST_GS_SEL,
	ACRN_VMCS_HOST_GS_BASE,
	ACRN_VMCS_HOST_TR_SEL,
	ACRN_VMCS_HOST_TR_BASE,
	ACRN_VMCS_HOST_GDTR_BASE,
	ACRN_VMCS_HOST_IDTR_BASE,
	ACRN_VMCS_HOST_RSP,
	ACRN_VMCS_HOST_RIP,
	ACRN_VMCS_HOST_PAT,
	ACRN_VMCS_HOST_EFER,
	ACRN_VMCS_HOST_PERF_G_CTRL,
	ACRN_VMCS_HOST_SYSENTER_CS,         // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_HOST_SYSENTER_ESP,        // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_HOST_SYSENTER_EIP,        // init as 0 (see dirty_bitmap in vmcs_create)

	ACRN_VMCS_HOST_END
} vmcs_host_field_t;

typedef enum {
	ACRN_VMCS_PIN_CTRL = ACRN_VMCS_HOST_END,
	ACRN_VMCS_PROC_CTRL1,
	ACRN_VMCS_PROC_CTRL2,
	ACRN_VMCS_EXCEPTION_BITMAP,
	ACRN_VMCS_IO_BITMAP_A,
	ACRN_VMCS_IO_BITMAP_B,
	ACRN_VMCS_TSC_OFFSET,
	ACRN_VMCS_CR0_MASK,
	ACRN_VMCS_CR4_MASK,
	ACRN_VMCS_CR0_SHADOW,
	ACRN_VMCS_CR4_SHADOW,
	ACRN_VMCS_CR3_TARGET0,
	ACRN_VMCS_CR3_TARGET1,
	ACRN_VMCS_CR3_TARGET2,
	ACRN_VMCS_CR3_TARGET3,
	ACRN_VMCS_CR3_TARGET_COUNT,
        ACRN_VMCS_APIC_ACCESS_ADDR,
	ACRN_VMCS_VIRTUAL_APIC_ADDR,
        ACRN_VMCS_TPR_THRESHOLD,
	ACRN_VMCS_EOI_EXIT_BITMAP0,
        ACRN_VMCS_EOI_EXIT_BITMAP1,
        ACRN_VMCS_EOI_EXIT_BITMAP2,
        ACRN_VMCS_EOI_EXIT_BITMAP3,
	ACRN_VMCS_POST_INTR_NOTI_VECTOR,
        ACRN_VMCS_POST_INTR_DESC_ADDR,
	ACRN_VMCS_MSR_BITMAP,
	ACRN_VMCS_EXECUTIVE_VMCS_PTR,
	ACRN_VMCS_EPTP_ADDRESS,
	ACRN_VMCS_VPID,
	ACRN_VMCS_PLE_GAP,
	ACRN_VMCS_PLE_WINDOW,
	ACRN_VMCS_VMFUNC_CTRL,
	ACRN_VMCS_EPTP_LIST_ADDR,
	ACRN_VMCS_VMREAD_BITMAP_ADDR,
	ACRN_VMCS_VMWRITE_BITMAP_ADDR,
	ACRN_VMCS_ENCLS_EXIT_BITMAP,
	ACRN_VMCS_PML_ADDR,
	ACRN_VMCS_VIRT_EXCEPT_INFO_ADDR,
	ACRN_VMCS_EPTP_INDEX,
	ACRN_VMCS_XSS_EXIT_BITMAP,

	ACRN_VMCS_EXEC_CTRL_END
} vmcs_exec_ctrl_field_t;

typedef enum {
	ACRN_VMCS_EXIT_CTRL = ACRN_VMCS_EXEC_CTRL_END,
	ACRN_VMCS_EXIT_MSR_STORE_COUNT,     // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_EXIT_MSR_STORE_ADDR,      // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_EXIT_MSR_LOAD_COUNT,      // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_EXIT_MSR_LOAD_ADDR,       // init as 0 (see dirty_bitmap in vmcs_create)

	ACRN_VMCS_EXIT_CTRL_END
} vmcs_exit_crtl_field_t;

typedef enum {
	ACRN_VMCS_ENTRY_CTRL = ACRN_VMCS_EXIT_CTRL_END,
	ACRN_VMCS_ENTRY_MSR_LOAD_COUNT,     // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_ENTRY_MSR_LOAD_ADDR,      // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_ENTRY_INTR_INFO,          // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_ENTRY_ERR_CODE,           // init as 0 (see dirty_bitmap in vmcs_create)
	ACRN_VMCS_ENTRY_INSTR_LEN,

	ACRN_VMCS_ENTRY_CTRL_END,
} vmcs_entry_ctrl_field_t;

typedef enum {
	ACRN_VMCS_EXIT_REASON = ACRN_VMCS_ENTRY_CTRL_END,
	ACRN_VMCS_EXIT_QUAL,
	ACRN_VMCS_EXIT_INT_INFO,
	ACRN_VMCS_EXIT_INT_ERR_CODE,
	ACRN_VMCS_IDT_VECTOR_INFO,
	ACRN_VMCS_IDT_VECTOR_ERR_CODE,
	ACRN_VMCS_EXIT_INSTR_LEN,
	ACRN_VMCS_EXIT_INSTR_INFO,
	ACRN_VMCS_GUEST_PHY_ADDR,
	ACRN_VMCS_GUEST_LINEAR_ADDR,
	ACRN_VMCS_INSTR_ERROR,

	ACRN_VMCS_VMEXIT_INFO_END
} vmcs_vmexit_info_field_t;




static vmcs_encoding_t g_field_data[] = {
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_VPID,                      0x00000000),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_IO_BITMAP_A,               0x00002000),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_IO_BITMAP_B,               0x00002002),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_MSR_BITMAP,                0x00002004),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_TSC_OFFSET,                0x00002010),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_VIRTUAL_APIC_ADDR,         0x00002012), // for virtual apic
        CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_APIC_ACCESS_ADDR,          0x00002014), // for virtual apic
        CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_POST_INTR_NOTI_VECTOR,     0x00000002), // for virtual apic
        CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_POST_INTR_DESC_ADDR,       0x00002016), // for virtual apic
        CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EOI_EXIT_BITMAP0,          0x0000201C), // for virtual apic
        CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EOI_EXIT_BITMAP1,          0x0000201E), // for virtual apic
        CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EOI_EXIT_BITMAP2,          0x00002020), // for virtual apic
        CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EOI_EXIT_BITMAP3,          0x00002022), // for virtual apic
        CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_TPR_THRESHOLD,             0x0000401C), // for virtual apic
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EPTP_ADDRESS,              0x0000201A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_XSS_EXIT_BITMAP,           0x0000202C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_PIN_CTRL,                  0x00004000),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_PROC_CTRL1,                0x00004002),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_PROC_CTRL2,                0x0000401E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_CTRL,                 0x0000400C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_CR0_MASK,                  0x00006000),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_CR4_MASK,                  0x00006002),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_CR0_SHADOW,                0x00006004),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_CR4_SHADOW,                0x00006006),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_CR3_TARGET0,               0x00006008),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_CR3_TARGET1,               0x0000600A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_CR3_TARGET2,               0x0000600C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_CR3_TARGET3,               0x0000600E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_LINK_PTR,                  0x00002800),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXECUTIVE_VMCS_PTR,        0x0000200C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_PLE_GAP,                   0x00004020),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_PLE_WINDOW,                0x00004022),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_VMFUNC_CTRL,               0x00002018),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EPTP_LIST_ADDR,            0x00002024),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_VMREAD_BITMAP_ADDR,        0x00002026),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_VMWRITE_BITMAP_ADDR,       0x00002028),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_ENCLS_EXIT_BITMAP,         0x0000202E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_PML_ADDR,                  0x0000200E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_VIRT_EXCEPT_INFO_ADDR,     0x0000202A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EPTP_INDEX,                0x00000004),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_CR0,                  0x00006C00),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_CR3,                  0x00006C02),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_CR4,                  0x00006C04),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_ES_SEL,               0x00000C00),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_CS_SEL,               0x00000C02),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_SS_SEL,               0x00000C04),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_DS_SEL,               0x00000C06),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_FS_SEL,               0x00000C08),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_FS_BASE,              0x00006C06),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_GS_SEL,               0x00000C0A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_GS_BASE,              0x00006C08),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_TR_SEL,               0x00000C0C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_TR_BASE,              0x00006C0A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_GDTR_BASE,            0x00006C0C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_IDTR_BASE,            0x00006C0E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_RSP,                  0x00006C14),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_RIP,                  0x00006C16),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_PAT,                  0x00002C00),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_EFER,                 0x00002C02),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_PERF_G_CTRL,          0x00002C04),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_MSR_STORE_COUNT,      0x0000400E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_MSR_STORE_ADDR,       0x00002006),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_MSR_LOAD_COUNT,       0x00004010),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_MSR_LOAD_ADDR,        0x00002008),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_ENTRY_MSR_LOAD_COUNT,      0x00004014),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_ENTRY_MSR_LOAD_ADDR,       0x0000200A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXCEPTION_BITMAP,          0x00004004),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_SYSENTER_CS,          0x00004C00),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_SYSENTER_ESP,         0x00006C10),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_HOST_SYSENTER_EIP,         0x00006C12),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_CR3_TARGET_COUNT,          0x0000400A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_ENTRY_INTR_INFO,           0x00004016),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_DBGCTL,              0x00002802),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_INTERRUPTIBILITY,    0x00004824),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_INTERRUPT_STATUS,    0x00000810), //for virtual apic
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_PEND_DBG_EXCEPTION,  0x00006822),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_ENTRY_ERR_CODE,            0x00004018),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_ENTRY_CTRL,                0x00004012),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_ENTRY_INSTR_LEN,           0x0000401A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_PREEMPTION_TIMER,          0x0000482E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_PAT,                 0x00002804),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_EFER,                0x00002806),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_PERF_G_CTRL,         0x00002808),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_PDPTR0,              0x0000280A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_PDPTR1,              0x0000280C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_PDPTR2,              0x0000280E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_PDPTR3,              0x00002810),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_CR0,                 0x00006800),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_CR3,                 0x00006802),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_CR4,                 0x00006804),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_DR7,                 0x0000681A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_GDTR_BASE,           0x00006816),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_GDTR_LIMIT,          0x00004810),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_IDTR_BASE,           0x00006818),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_IDTR_LIMIT,          0x00004812),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_ACTIVITY_STATE,      0x00004826),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_SYSENTER_CS,         0x0000482A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_SYSENTER_ESP,        0x00006824),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_SYSENTER_EIP,        0x00006826),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_ES_SEL,              0x00000800),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_ES_BASE,             0x00006806),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_ES_LIMIT,            0x00004800),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_ES_AR,               0x00004814),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_CS_SEL,              0x00000802),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_CS_BASE,             0x00006808),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_CS_LIMIT,            0x00004802),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_CS_AR,               0x00004816),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_SS_SEL,              0x00000804),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_SS_BASE,             0x0000680A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_SS_LIMIT,            0x00004804),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_SS_AR,               0x00004818),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_DS_SEL,              0x00000806),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_DS_BASE,             0x0000680C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_DS_LIMIT,            0x00004806),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_DS_AR,               0x0000481A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_FS_SEL,              0x00000808),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_FS_BASE,             0x0000680E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_FS_LIMIT,            0x00004808),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_FS_AR,               0x0000481C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_GS_SEL,              0x0000080A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_GS_BASE,             0x00006810),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_GS_LIMIT,            0x0000480A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_GS_AR,               0x0000481E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_LDTR_SEL,            0x0000080C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_LDTR_BASE,           0x00006812),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_LDTR_LIMIT,          0x0000480C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_LDTR_AR,             0x00004820),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_TR_SEL,              0x0000080E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_TR_BASE,             0x00006814),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_TR_LIMIT,            0x0000480E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_TR_AR,               0x00004822),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_RSP,                 0x0000681C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_RIP,                 0x0000681E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_RFLAGS,              0x00006820),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_PHY_ADDR,            0x00002400),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_GUEST_LINEAR_ADDR,         0x0000640A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_INSTR_ERROR,               0x00004400),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_REASON,               0x00004402),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_INT_INFO,             0x00004404),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_INT_ERR_CODE,         0x00004406),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_IDT_VECTOR_INFO,           0x00004408),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_IDT_VECTOR_ERR_CODE,       0x0000440A),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_INSTR_LEN,            0x0000440C),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_INSTR_INFO,           0x0000440E),
	CONSTRUCT_ACRN_VMCS_ENCODING(ACRN_VMCS_EXIT_QUAL,                 0x00006400)
};

void print_vmcs_all(struct acrn_vcpu *vcpu)
{
	uint32_t i =0;
	uint64_t val;
	struct acrn_vcpu *sos_vcpu = NULL;

#if 0
	for (i = 0; i < ACRN_VMCS_FIELD_COUNT; ++i) {
		val = exec_vmread(g_field_data[i].encoding);
		pr_err("%40s (0x%04X) = hw_value(0x%llX)\n", g_field_data[i].name, g_field_data[i].encoding, val);
	}
#endif

	foreach_vcpu(i, get_sos_vm(), sos_vcpu) {
		if (sos_vcpu != vcpu)
			pause_vcpu(sos_vcpu, VCPU_ZOMBIE);
	}

	printf("\n  VM[%d]  VCPU[%d] PCPU[%d]:", vcpu->vm->vm_id, vcpu->vcpu_id, vcpu->pcpu_id);

	printf("\n********************************* ACRN VMCS EXEC CONTROL Fields ******************************\n");
	for (i = ACRN_VMCS_HOST_END; i < ACRN_VMCS_EXEC_CTRL_END; i++) {
		val = exec_vmread(g_field_data[i].encoding);
		printf("%40s (0x%04X) = 0x%llX\n", g_field_data[i].name, g_field_data[i].encoding, val);
	}
	printf("################################## ACRN VMCS EXEC CONTROL Fields ##############################\n");

	printf("\n********************************* ACRN VMCS EXIT CONTROL Fields ******************************\n");
	for (i = ACRN_VMCS_EXEC_CTRL_END; i < ACRN_VMCS_EXIT_CTRL_END; i++) {
		val = exec_vmread(g_field_data[i].encoding);
		printf("%40s (0x%04X) = 0x%llX\n", g_field_data[i].name, g_field_data[i].encoding, val);
	}
	printf("################################## ACRN VMCS EXIT CONTROL Fields ##############################\n");

	printf("\n********************************* ACRN VMCS ENTRY CONTROL Fields ******************************\n");
	for (i = ACRN_VMCS_EXIT_CTRL_END; i < ACRN_VMCS_ENTRY_CTRL_END; i++) {
		val = exec_vmread(g_field_data[i].encoding);
		printf("%40s (0x%04X) = 0x%llX\n", g_field_data[i].name, g_field_data[i].encoding, val);
	}
	printf("################################## ACRN VMCS ENTRY CONTROL Fields ##############################\n");

	foreach_vcpu(i, get_sos_vm(), sos_vcpu) {
		if (sos_vcpu != vcpu)
			resume_vcpu(sos_vcpu);
	}
}
